name: Deploy Vue Project

on:
  push:
    branches: [ master ] # 触发分支，根据你的分支名称调整

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # 使用你项目所需的 Node.js 版本

      - name: Install dependencies
        run: npm install

      - name: Build Vue project
        run: npm run build # 假设你的构建命令是 npm run build

      - name: Deploy to server via SSH
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # 配置 SSH 密钥
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no" > ~/.ssh/config

          # 上传构建文件到服务器（使用 scp，可替换为 rsync）
          scp -r ./dist/* "$SERVER_USER"@"$SERVER_IP":"$DEPLOY_PATH"
